### ISSUE TITLE
Contact email not working

### ISSUE THREAD

**Issue by demenech** [datopian/datahub-next#114]
_Reported by @ jrdunson on Discord._

There's a contact email on the footer on https://datahub.io/ which is not working: support@datahub.io 

![image](https://user-images.githubusercontent.com/16550934/231159772-03477fac-9cbb-486c-bc9c-9b503953a584.png)

## Acceptance

- [x] I can receive and see emails sent to support@datahub.io

**Comment by rufuspollock** [comment]
@demenech @anuveyatsu did this get fixed?

**Comment by demenech** [comment]
@rufuspollock I just tried it out again and this is still happening. Who could verify this? CC: @anuveyatsu

**Comment by anuveyatsu** [comment]
@rufuspollock @demenech I can see that MX record for the domain on cloudflare is pointing to dreamhost which means that email server is there and probably we stopped our account or similar so it is broken.

My suggestion is to use Cloudflare's Email routing which I have just done - now emails to support@datahub.io lands on contact@datopian.com:

<img width="1440" alt="Screenshot 2023-10-12 at 12 26 28 PM" src="https://github.com/datopian/datahub-next/assets/17809581/32e319db-3641-4a32-a8fb-4fe1212dac25">

**Comment by anuveyatsu** [comment]
FIXED, now emails sent to support@datahub.io go to contact@datopian.com
