### ISSUE TITLE
DataTable v0.2: Filtering, Sorting, Pagination/Scrolling

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#29]
We want to improve the data table we have implemented in #5 

Also feel free to quickly check out ag-grid if we think it will give us more mileage a lot faster.

## Acceptance

- [x] Filtering (simple google style i.e. a single text box that applies to everything) **✅ 2023-06-2023 added a global filter as a text input, PR: https://github.com/datopian/datahub-next/pull/30**
- [x] Sorting **✅ 2023-06-2023 added basic column sorting (click on column name to sort), PR: https://github.com/datopian/datahub-next/pull/30**
- [x] Works with quite a lot of data (so doesn't crash browser by rendering all the divs) i.e. virtualized infinite scroll or pagination **✅ 2023-06-2023 added basic pagination, with arrow buttons, PR: https://github.com/datopian/datahub-next/pull/30**

## Notes
![image](https://user-images.githubusercontent.com/16550934/223241480-8950a007-1a9c-4d98-aaf0-ef8b849b68f4.png)
![image](https://user-images.githubusercontent.com/16550934/223241541-a8dab404-d530-4796-a30b-38c17fac7d1e.png)
![image](https://user-images.githubusercontent.com/16550934/223241601-387a1443-5844-4e7e-b9f8-22dc4c6618e7.png)

**Comment by demenech** [comment]
**Update:** basic implementation is done. Tomorrow I will investigate why the E2E test is falling for the PR (https://github.com/datopian/datahub-next/pull/30) and assign @olayway as the reviewer. Also thinking about adding a bigger margin for the global search input.

**Comment by demenech** [comment]
**Update:** deploy and tests fixed, waiting for the review and merge of the PR (https://github.com/datopian/datahub-next/pull/30)

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/1c4b575ec5ea13c30d92d085c1f45394b37de71e.
