### ISSUE TITLE
Missing logo image

### ISSUE THREAD

**Issue by davidgasquez** [datopian/datahub-next#40]
This link is broken: https://github.com/datopian/datahub-next/blob/14be410d8aef1d6539152fa77b6e8606d407e69a/content/docs/dms/index.md?plain=1#L5. 

Couldn't find a replacement for `datopian-dark-logotype.svg` in the org.

**Comment by demenech** [comment]
Hello @davidgasquez 

Thank you for flagging

___

**FIXED.** See https://datahub.io/docs/dms/
