### ISSUE TITLE
Convert to typescript (at least for new code)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#7]
Current stuff from old data literate / portaljs is in JS not typescript.

## Acceptance

- [x] There is a tsconfig.json file **✅ 2023-04-04 Fixed. See commit https://github.com/datopian/datahub-next/commit/68abf8317d8527acfcf686623bd42c8a7cce96cb**
- [x] `.ts` and `.tsx` files work as expected

**Comment by rufuspollock** [comment]
@demenech what's left here?

**Comment by rufuspollock** [comment]
@demenech ok please change acceptance and close.

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/68abf8317d8527acfcf686623bd42c8a7cce96cb. TS files are working as expected and we are renaming files to .ts and .tsx as we go.
